# CMake generated Testfile for 
# Source directory: D:/homegrowh_harness/package/tools/filesystems
# Build directory: D:/homegrowh_harness/build-windows
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[file_reader_test]=] "D:/homegrowh_harness/build-windows/Debug/file_reader.exe")
  set_tests_properties([=[file_reader_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/homegrowh_harness/package/tools/filesystems/CMakeLists.txt;179;add_test;D:/homegrowh_harness/package/tools/filesystems/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[file_reader_test]=] "D:/homegrowh_harness/build-windows/Release/file_reader.exe")
  set_tests_properties([=[file_reader_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/homegrowh_harness/package/tools/filesystems/CMakeLists.txt;179;add_test;D:/homegrowh_harness/package/tools/filesystems/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[file_reader_test]=] "D:/homegrowh_harness/build-windows/MinSizeRel/file_reader.exe")
  set_tests_properties([=[file_reader_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/homegrowh_harness/package/tools/filesystems/CMakeLists.txt;179;add_test;D:/homegrowh_harness/package/tools/filesystems/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[file_reader_test]=] "D:/homegrowh_harness/build-windows/RelWithDebInfo/file_reader.exe")
  set_tests_properties([=[file_reader_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/homegrowh_harness/package/tools/filesystems/CMakeLists.txt;179;add_test;D:/homegrowh_harness/package/tools/filesystems/CMakeLists.txt;0;")
else()
  add_test([=[file_reader_test]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[file_edit_test]=] "D:/homegrowh_harness/build-windows/Debug/file_edit.exe")
  set_tests_properties([=[file_edit_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/homegrowh_harness/package/tools/filesystems/CMakeLists.txt;184;add_test;D:/homegrowh_harness/package/tools/filesystems/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[file_edit_test]=] "D:/homegrowh_harness/build-windows/Release/file_edit.exe")
  set_tests_properties([=[file_edit_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/homegrowh_harness/package/tools/filesystems/CMakeLists.txt;184;add_test;D:/homegrowh_harness/package/tools/filesystems/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[file_edit_test]=] "D:/homegrowh_harness/build-windows/MinSizeRel/file_edit.exe")
  set_tests_properties([=[file_edit_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/homegrowh_harness/package/tools/filesystems/CMakeLists.txt;184;add_test;D:/homegrowh_harness/package/tools/filesystems/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[file_edit_test]=] "D:/homegrowh_harness/build-windows/RelWithDebInfo/file_edit.exe")
  set_tests_properties([=[file_edit_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/homegrowh_harness/package/tools/filesystems/CMakeLists.txt;184;add_test;D:/homegrowh_harness/package/tools/filesystems/CMakeLists.txt;0;")
else()
  add_test([=[file_edit_test]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[watch_file_test]=] "D:/homegrowh_harness/build-windows/Debug/watch_file.exe")
  set_tests_properties([=[watch_file_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/homegrowh_harness/package/tools/filesystems/CMakeLists.txt;189;add_test;D:/homegrowh_harness/package/tools/filesystems/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[watch_file_test]=] "D:/homegrowh_harness/build-windows/Release/watch_file.exe")
  set_tests_properties([=[watch_file_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/homegrowh_harness/package/tools/filesystems/CMakeLists.txt;189;add_test;D:/homegrowh_harness/package/tools/filesystems/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[watch_file_test]=] "D:/homegrowh_harness/build-windows/MinSizeRel/watch_file.exe")
  set_tests_properties([=[watch_file_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/homegrowh_harness/package/tools/filesystems/CMakeLists.txt;189;add_test;D:/homegrowh_harness/package/tools/filesystems/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[watch_file_test]=] "D:/homegrowh_harness/build-windows/RelWithDebInfo/watch_file.exe")
  set_tests_properties([=[watch_file_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/homegrowh_harness/package/tools/filesystems/CMakeLists.txt;189;add_test;D:/homegrowh_harness/package/tools/filesystems/CMakeLists.txt;0;")
else()
  add_test([=[watch_file_test]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[chunk_matcher_stress_test]=] "D:/homegrowh_harness/build-windows/Debug/chunk_matcher_stress.exe")
  set_tests_properties([=[chunk_matcher_stress_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/homegrowh_harness/package/tools/filesystems/CMakeLists.txt;194;add_test;D:/homegrowh_harness/package/tools/filesystems/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[chunk_matcher_stress_test]=] "D:/homegrowh_harness/build-windows/Release/chunk_matcher_stress.exe")
  set_tests_properties([=[chunk_matcher_stress_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/homegrowh_harness/package/tools/filesystems/CMakeLists.txt;194;add_test;D:/homegrowh_harness/package/tools/filesystems/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[chunk_matcher_stress_test]=] "D:/homegrowh_harness/build-windows/MinSizeRel/chunk_matcher_stress.exe")
  set_tests_properties([=[chunk_matcher_stress_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/homegrowh_harness/package/tools/filesystems/CMakeLists.txt;194;add_test;D:/homegrowh_harness/package/tools/filesystems/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[chunk_matcher_stress_test]=] "D:/homegrowh_harness/build-windows/RelWithDebInfo/chunk_matcher_stress.exe")
  set_tests_properties([=[chunk_matcher_stress_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/homegrowh_harness/package/tools/filesystems/CMakeLists.txt;194;add_test;D:/homegrowh_harness/package/tools/filesystems/CMakeLists.txt;0;")
else()
  add_test([=[chunk_matcher_stress_test]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[windows_edit_stress_smoke_test]=] "D:/homegrowh_harness/build-windows/Debug/windows_edit_stress.exe" "--profile" "smoke" "--output" "D:/homegrowh_harness/build-windows/windows-edit-stress-results")
  set_tests_properties([=[windows_edit_stress_smoke_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/homegrowh_harness/package/tools/filesystems/CMakeLists.txt;201;add_test;D:/homegrowh_harness/package/tools/filesystems/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[windows_edit_stress_smoke_test]=] "D:/homegrowh_harness/build-windows/Release/windows_edit_stress.exe" "--profile" "smoke" "--output" "D:/homegrowh_harness/build-windows/windows-edit-stress-results")
  set_tests_properties([=[windows_edit_stress_smoke_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/homegrowh_harness/package/tools/filesystems/CMakeLists.txt;201;add_test;D:/homegrowh_harness/package/tools/filesystems/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[windows_edit_stress_smoke_test]=] "D:/homegrowh_harness/build-windows/MinSizeRel/windows_edit_stress.exe" "--profile" "smoke" "--output" "D:/homegrowh_harness/build-windows/windows-edit-stress-results")
  set_tests_properties([=[windows_edit_stress_smoke_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/homegrowh_harness/package/tools/filesystems/CMakeLists.txt;201;add_test;D:/homegrowh_harness/package/tools/filesystems/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[windows_edit_stress_smoke_test]=] "D:/homegrowh_harness/build-windows/RelWithDebInfo/windows_edit_stress.exe" "--profile" "smoke" "--output" "D:/homegrowh_harness/build-windows/windows-edit-stress-results")
  set_tests_properties([=[windows_edit_stress_smoke_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/homegrowh_harness/package/tools/filesystems/CMakeLists.txt;201;add_test;D:/homegrowh_harness/package/tools/filesystems/CMakeLists.txt;0;")
else()
  add_test([=[windows_edit_stress_smoke_test]=] NOT_AVAILABLE)
endif()
subdirs("_deps/cli11-build")
subdirs("_deps/nlohmann_json-build")
